# -*- coding: utf-8 -*-
"""Cotton_Master_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_l-lbn37xsRp5VIP1KBXKgN8wWw08syU
"""

import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error

# =====================
# Load Data
# =====================
DATA_PATH = "/content/Cotton_Master_Dataset (1).xlsx"
df = pd.read_excel(DATA_PATH)

# =====================
# Encode Growth Stage
# =====================
stage_encoder = LabelEncoder()
df["stage_enc"] = stage_encoder.fit_transform(df["growth_stage"])

# =====================
# Features
# =====================
FEATURE_COLUMNS = [
    "vegetation_stress_score",
    "water_stress_score",
    "soil_stress_score",
    "final_stress_percent",
    "gdd_min",
    "gdd_max",
    "stage_enc"
]

X = df[FEATURE_COLUMNS]

# =====================
# Targets (Cotton Diseases)
# =====================
TARGET_COLUMNS = [
    "damping_off",
    "root_rot",
    "bacterial_blight",
    "alternaria_leaf_spot",
    "fusarium_wilt",
    "verticillium_wilt",
    "boll_rot"
]

y = df[TARGET_COLUMNS]

# =====================
# Train Test Split
# =====================
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# =====================
# Scaling
# =====================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# =====================
# Model
# =====================
ann_model = MLPRegressor(
    hidden_layer_sizes=(64, 32),   # slightly improved
    activation="relu",
    solver="adam",
    learning_rate="adaptive",
    max_iter=1500,
    random_state=42,
    early_stopping=True
)

# =====================
# Training
# =====================
ann_model.fit(X_train_scaled, y_train)

# =====================
# Evaluation
# =====================
y_pred = ann_model.predict(X_test_scaled)
mae = mean_absolute_error(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.4f}")

# =====================
# Save Model & Objects
# =====================
with open("cotton_ann_model.pkl", "wb") as f:
    pickle.dump(ann_model, f)

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

with open("stage_encoder.pkl", "wb") as f:
    pickle.dump(stage_encoder, f)

print("✅ Cotton ANN multi-disease model saved successfully.")